.\" Copyright (C) 2005-2008 Giuseppe Baruffa
.\"
.\" This file is part of Pyuv.
.\"
.TH Pyuv "1"
.SH NAME
Pyuv \- Raw sequence player.
.SH SYNOPSIS
.nf
pyuv [options]
.fi
.SH OPTIONS
The only admitted option is the filename to open
.nf

    pyuv filename.extension

.fi
For a more thorough help consult the HTML help by pressing CTRL+H.
.SH DESCRIPTION
Pyuv is a program that may be used to view raw uncompressed sequence
written as an headerless bunch of bytes on a single file.
.SH DOCUMENTATION
Read the README file.

.SH BUGS
The best way to submit a bug report for Pyuv is to send a mail to
.B baruffa@diei.unipg.it

.SH AUTHOR
.nf
Giuseppe Baruffa
Department of Electronic and Information Engineering
University of Perugia
Perugia, IT 06125
Italy
<baruffa@diei.unipg.it>
.fi
